services:
  - type: web
    name: product-searcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BSAgdn1sl1bYrniqvGdpRAefrqF5glX
        fromDatabase:
          name: product_searcher_db
          property: BSAgdn1sl1bYrniqvGdpRAefrqF5glX
      - key: PORT
        value: "10000"
    plan: free
